version: '3.8'

services:
    db:
        container_name: ultratest_db
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - ultratest-network
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}         
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}  
    dev:
        container_name: ultratest_dev
        image: ultratest-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: sh -c "npm run typeorm migration:run && npm run start:debug"
        ports:
            - ${APP_PORT}:${APP_PORT}
            - 9229:9229
        networks:
            - ultratest-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - db
networks:
    ultratest-network:
volumes:
    mysql_data:
        name: mysql_data

